apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: my-otel-demo
    meta.helm.sh/release-namespace: otel-demo
  creationTimestamp: "2023-09-06T13:18:28Z"
  generation: 1
  labels:
    tags.datadoghq.com/env: otel-demo
    tags.datadoghq.com/service: currencyservice
    tags.datadoghq.com/version: 1.4.0   
    app.kubernetes.io/component: currencyservice
    app.kubernetes.io/instance: my-otel-demo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: my-otel-demo-currencyservice
    app.kubernetes.io/part-of: opentelemetry-demo
    app.kubernetes.io/version: 1.4.0
    helm.sh/chart: opentelemetry-demo-0.23.0
    opentelemetry.io/name: my-otel-demo-currencyservice
  name: my-otel-demo-currencyservice
  namespace: otel-demo
  resourceVersion: "27294126"
  uid: 260b129a-55e5-475f-9c57-1c0114186cc6
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      opentelemetry.io/name: my-otel-demo-currencyservice
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        tags.datadoghq.com/env: otel-demo
        tags.datadoghq.com/service: currencyservice
        tags.datadoghq.com/version: 1.4.0      
        app.kubernetes.io/component: currencyservice
        app.kubernetes.io/instance: my-otel-demo
        app.kubernetes.io/name: my-otel-demo-currencyservice
        opentelemetry.io/name: my-otel-demo-currencyservice
    spec:
      containers:
      - env:
        - name: OTEL_SERVICE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['app.kubernetes.io/component']
        - name: OTEL_K8S_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: OTEL_K8S_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: OTEL_K8S_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: OTEL_K8S_POD_UID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.uid
        - name: OTEL_COLLECTOR_NAME
          value: my-otel-demo-otelcol
        - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
          value: cumulative
        - name: CURRENCY_SERVICE_PORT
          value: "8080"
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://$(HOST_IP):4317
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: service.name=$(OTEL_SERVICE_NAME),service.instance.id=$(OTEL_K8S_POD_UID),service.namespace=opentelemetry-demo,k8s.namespace.name=$(OTEL_K8S_NAMESPACE),k8s.node.name=$(OTEL_K8S_NODE_NAME),k8s.pod.name=$(OTEL_K8S_POD_NAME),deployment.environment=otel-demo,service.version=1.4.0
        image: ghcr.io/open-telemetry/demo:1.4.0-currencyservice
        imagePullPolicy: IfNotPresent
        name: currencyservice
        ports:
        - containerPort: 8080
          name: service
          protocol: TCP
        resources:
          limits:
            memory: 20Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: my-otel-demo
      serviceAccountName: my-otel-demo
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-09-06T13:18:31Z"
    lastUpdateTime: "2023-09-06T13:18:31Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-09-06T13:18:28Z"
    lastUpdateTime: "2023-09-06T13:18:31Z"
    message: ReplicaSet "my-otel-demo-currencyservice-848cd7bbd5" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
